import type {
  InspectionSettings,
  LongFormSettings,
  ReferenceCategory,
  ReferenceEntry,
  SceneDesign,
  Work,
  WorkBundle,
  WorkPreference,
} from "./types";

export const defaultLongFormSettings = (): LongFormSettings => ({
  targetChapters: 12,
  finalResolutionMinScene: 30,
  finalResolutionMinProgress: 75,
  minOpenThreads: 3,
  maxChangesPerScene: 3,
  maxConsecutiveSceneType: 3,
  warnInstantSuccess: true,
  hardLock: false,
});
export const defaultSceneDesign = (): SceneDesign => ({
  purpose: "",
  povCharacterId: "",
  characterIds: [],
  locationId: "",
  openingSituation: "",
  obstacle: "",
  attempt: "",
  result: "",
  endingChange: "",
  sceneType: "その他",
  timeline: "",
  hasFullResolution: false,
  createsNewProblem: false,
  revealsInformation: false,
  changesRelationship: false,
  changesItemOrState: false,
  multipleLocations: false,
  majorTimePassage: false,
  outcomeSuccessful: false,
});
export const defaultInspectionSettings = (): InspectionSettings => ({
  longParagraph: 400,
  shortParagraph: 20,
  shortParagraphRun: 4,
  longSentence: 160,
  punctuationless: 120,
  repetitionWindow: 300,
  repetitionParagraphs: 3,
  excludedWords: ["こと", "もの", "ため", "よう", "それ", "これ", "そして"],
  trackedWords: [],
});
export const defaultWorkPreference = (
  workId: string,
  id = workId,
): WorkPreference => ({
  id,
  workId,
  inspection: defaultInspectionSettings(),
  snapshotLimit: 20,
  backupReminderDays: 14,
  lastBackupAt: "",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
});
export const normalizeWork = (work: Work): Work => ({
  ...work,
  longFormSupport: work.longFormSupport ?? false,
  targetCharacters: work.targetCharacters ?? 80000,
  targetScenes: work.targetScenes ?? 40,
  longFormSettings: {
    ...defaultLongFormSettings(),
    ...(work.longFormSettings || {}),
  },
});
export const normalizeBundle = (
  bundle: Partial<WorkBundle> &
    Pick<WorkBundle, "work" | "chapters" | "scenes">,
): WorkBundle => ({
  work: normalizeWork(bundle.work),
  chapters: bundle.chapters || [],
  scenes: (bundle.scenes || []).map((s) => ({
    ...s,
    design: { ...defaultSceneDesign(), ...(s.design || {}) },
    bodyUpdatedAt: s.bodyUpdatedAt || s.updatedAt,
    designUpdatedAt: s.designUpdatedAt || s.updatedAt,
  })),
  references: (bundle.references || []).map((reference) => ({
    ...reference,
    characterProfile: reference.characterProfile || {},
  })),
  relationships: bundle.relationships || [],
  foreshadows: bundle.foreshadows || [],
  questions: bundle.questions || [],
  promises: bundle.promises || [],
  subplots: bundle.subplots || [],
  warningPreferences: bundle.warningPreferences || [],
  spellingRules: bundle.spellingRules || [],
  workPreferences: (bundle.workPreferences || []).map((p) => ({
    ...defaultWorkPreference(p.workId, p.id),
    ...p,
    inspection: { ...defaultInspectionSettings(), ...(p.inspection || {}) },
  })),
  timelineEvents: bundle.timelineEvents || [],
  knowledgeItems: bundle.knowledgeItems || [],
  branchIdeas: bundle.branchIdeas || [],
  writingLogs: bundle.writingLogs || [],
});
export function emptyReference(
  category: ReferenceCategory,
  workId: string,
  id: string,
  time: string,
): ReferenceEntry {
  return {
    id,
    workId,
    category,
    name: "",
    reading: "",
    aliases: "",
    role: "",
    age: "",
    gender: "",
    appearance: "",
    personality: "",
    objective: "",
    desire: "",
    fear: "",
    secret: "",
    history: "",
    speech: "",
    firstPerson: "",
    secondPerson: "",
    importance: "その他",
    firstSceneId: "",
    relatedSceneIds: [],
    kind: "",
    description: "",
    atmosphere: "",
    region: "",
    relatedCharacterIds: [],
    memberCharacterIds: [],
    relations: "",
    ownerCharacterId: "",
    foreshadowId: "",
    relatedEntryIds: [],
    tags: [],
    notes: "",
    characterProfile: {},
    createdAt: time,
    updatedAt: time,
  };
}
